spring.application.name=agrosat-rest-api
server.port=8081

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=RM99856
spring.datasource.password=280105
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.agrosatmonitor=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ws=DEBUG

# AuthApi integration
auth.api.url=http://localhost:8080
auth.api.validate-endpoint=/auth/validate

# SOAP Service integration
soap.service.url=http://localhost:8082/ws
soap.service.namespace=http://agrosatmonitor.com/soap

# External APIs
openmeteo.api.url=https://api.open-meteo.com/v1/forecast
openmeteo.api.timeout=10000

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# HikariCP ? evita ORA-17008
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL